### ISSUE TITLE
Events seem loth to fire

### ISSUE THREAD

**Issue by DuoDex** [PropaneDragon/RushHour#16]
I have quite a few of the unique buildings that should be firing events and cause people to visit them, etc as I see in the code for events at the Expo Center and Stadium, but I am not getting any Chirper messages nor any appearance of events on the time bar.

I have tried to force events using the options menu, but since none have ever fired, none fire after the previous one is over.

Maybe add a button to fire an event?

**Comment by PropaneDragon** [comment]
Interesting. The code should make them fire if there's no event scheduled. What landmarks do you have in your city?

**Comment by DuoDex** [comment]
Every one in CityEventsBuildings.cs (I can read code, but damned if I can write it).

**Comment by PropaneDragon** [comment]
Could you send me your log? It should say when/if an event was scheduled.

**Comment by DuoDex** [comment]
I actually just left for work, but I will get it to you as soon as I can. player.log is the one right?

**Comment by PropaneDragon** [comment]
output_log.txt in steamapps\common\Cities_Skylines\Cities_Data. Chances are this won't really tell me anything unless you've only just started using the mod, but we'll see. I might have to add some more debugging.

**Comment by DuoDex** [comment]
Okay, thanks. Sorry for the confusion, I play Kerbal Space Program and output_log.txt is entirely useless to mod developers there.

**Comment by PropaneDragon** [comment]
No problem :)

**Comment by DuoDex** [comment]
After some poking, I figured that you want [player.log](https://gist.github.com/DuoDex/d851c557e942a74c463f) because I'm on Linux. 

I'm getting events now, but no messages in Chirpy. Inclined to blame SuperChirper for that after digging through the log a bit.

(also wow, Enhanced Hearse AI throws a lot of exceptions).

**Comment by PropaneDragon** [comment]
Thanks. I didn't realise Unity changed the log name per OS. I'll look into it now and see if I notice anything.

**Comment by PropaneDragon** [comment]
Ah, turns out that log is incomplete by the looks of things. Had you started your game when you copied it, as that replaces it as it goes. I'll get some more logging in soon, and I'll ask you to send me a log again after your game has loaded.

**Comment by DuoDex** [comment]
That should be complete, maybe Github truncated it accidentally or you were looking at the preview. Try [this](https://gist.githubusercontent.com/DuoDex/d851c557e942a74c463f/raw/97f8eb0e888b0b88154e2c63371aa1f54ecdd1eb/Player.log).

**Comment by PropaneDragon** [comment]
That one works. Looks like Linux does a ton more debugging too. After having a look over the logs (on my tablet, so I might have missed something. I'll have a look again tomorrow), I've noticed events are firing fine from what I can tell but I have noticed some things which may be causing problems:
- You have a mod called SuperChirper which is failing when it gets to displaying chirps for the events, which may be my issue, or SuperChirper. I'll look into this when I can, but this is why you're not seeing events.
- Enhanced hearse AI is completely failing to run, which might cause issues somewhere. Probably does nothing to this mod but you might want to investigate it.

Not sure why it's not showing on the date time bar. Is the custom one switched on in the settings? Also, try the mod again, as I've released an update. I'm not sure what this will do for this problem but you never know.

**Comment by PropaneDragon** [comment]
Just taken a look on the PC now, and so far I've not noticed anything else unusual. I'm not sure about what date your city is at now, but your last event was at 11:00:02 PM, 4/13/2016 at the Stadium. The one before that was at 11:00:00 AM, 4/10/2016, also at the Stadium.

**Comment by PropaneDragon** [comment]
Did this resolve the issue, or is it still a problem?

**Comment by DuoDex** [comment]
Ah, yeah, I haven't been playing C:S much recently, but tonight events do seem quite more likely to work. Thanks!
