### ISSUE TITLE
Almost no commuter traffic

### ISSUE THREAD

**Issue by psde** [PropaneDragon/RushHour#20]
My city with a population of about 80k I almost see no residential or commuter traffic, not even on a Monday morning (where almost everyone should go to work). The city does not have any public transit and almost all traffic is originating from commercial and industry. There is some traffic in my leisure/entertainment areas, but almost exclusively from tourists. 

One of my industry area is only accessible by highway and even tho there are no worker commuting there goods are getting created.

I first suspected this could be an issue with another mod as I was using Traffic Manager Presidential Edition and Realistic Population, but low traffic remains even without these mods.

**Comment by PropaneDragon** [comment]
This doesn't sound good. Are all the sliders where they should be? Try deleting the options xml file for the mod and try again. If none of those work, could I have your debug log?

**Comment by PropaneDragon** [comment]
Did you resolve this, or is this still an issue?

**Comment by psde** [comment]
I think this was an issue with another mod, starting a new city with only rush hour mod enabled resulted in (a lot of) commuter traffic. While re-enabling other mods did not result in any less traffic in the new city, the old city still does not generate any (even with only rush hour enabled) - maybe another mod (or the patch) broke something permanently.

**Comment by PropaneDragon** [comment]
What mods do you have?
