### ISSUE TITLE
Find a workaround for including CimTools in the mod

### ISSUE THREAD

**Issue by PropaneDragon** [PropaneDragon/RushHour#24]
I did a stupid and included the dll of CimTools in the mod from the get-go instead of adding it as a required mod. Because of this I need many different versions of CimTools to avoid any clashing with mods that use other versions.

We need a workaround or a good idea to either decrease the number of CimTools floating around there, or find a way of subscribing to a global CimTools mod without screwing around with the existing users.

**Comment by bloodypenguin** [comment]
Just do something like [this](https://github.com/earalov/Skylines-MoreFlags/blob/master/MoreFlags/LoadingExtension.cs#L147). User sees the popup and installs the mod.

**Comment by PropaneDragon** [comment]
I want to consider a way that doesn't nag the user before going down that route. I'd hate to force existing users to subscribe to another workshop item when they didn't have to originally, although it would make life easier for me.

I might put something in as soon as the mod is loaded if I have to do this, so it doesn't wait until they've gone through the whole city loading process first (which can take half an hour on some machines).

**Comment by PropaneDragon** [comment]
Found a way of doing it, but it's a bit convoluted and hacky so I decided against it. I'm just going to keep including CimTools in Rush Hour releases, but I change the namespace of the Rush Hour version so it doesn't conflict in the future.

See 3e4371356073bd9e45bb9cde9ed04012b45ca44d and 46cea0dfc3fc25763d06531b2e88d2890940ffb7
