### ISSUE TITLE
What branch to use?

### ISSUE THREAD

**Issue by riccardobecker** [PropaneDragon/RushHour#26]
Hi there,
I downloaded the release branch but that caused some errors in VS2015 like 
'DistrictPolicies.Policies' does not contain a definition for 'ExtraInsulation' 

thanks

**Comment by riccardobecker** [comment]
already fixed..had to download the latest skylines

**Comment by r4j4h** [comment]
Glad you got things fixed so easily =) Closing the issue, it should still come up in search if anyone looks for the error you included. :+1:

**Comment by riccardobecker** [comment]
Btw, a bit off-topic maybe but I am looking for good resources on building own mods. There doesn't seem to be much out there!

**Comment by PropaneDragon** [comment]
Documentation is very basic, but I'd begin with the wiki on CIties Skylines which says how to make a basic mod, then you should try decompiling some of the DLLs that Skylines uses as they've not obfuscated them thankfully. Unfortunately from there on out you have to pretty much work out how everything works from the decompiled code without comments.

**Comment by riccardobecker** [comment]
Yes that's a shame :-) I know the basics and I've managed to build some custom mods though. Hope someone has the time to create a proper tutorial though!
