### ISSUE TITLE
Please fix OnSettingsUI

### ISSUE THREAD

**Issue by SamsamTS** [PropaneDragon/RushHour#27]
Hi there PropaneDragon,

Can you please change
`UIButton componentInChildren = Resources.FindObjectsOfTypeAll<OptionsKeymappingPanel>()[0].GetComponentInChildren<UITabstrip>().GetComponentInChildren<UIButton>();`

to 

`UIButton componentInChildren = GameObject.Find("KeyMappingTabStrip").GetComponentInChildren<UIButton>();`

It is not safe. I cannot use OptionsKeymappingPanel because of this.

**Comment by PropaneDragon** [comment]
Sorry about that. I'm away for a week unfortunately, but I'll fix it as soon as I get back. Thanks for the fix.

**Comment by SamsamTS** [comment]
I end up copying the decompiled version of OptionsKeymappingPanel instead of inherit from it so it's all good now. I still wouldn't recommend the use of Resources.FindObjectsOfTypeAll because there is no guaranty that the first element is the one you want.

You can close this issue if you want.

**Comment by PropaneDragon** [comment]
This should be fixed now.
