### ISSUE TITLE
Idea: People should choose closest entertainment destination

### ISSUE THREAD

**Issue by bloodypenguin** [PropaneDragon/RushHour#3]
When people have choice of visiting some place they should prefer the closest to them

**Comment by cptalpdeniz** [comment]
But, what will happen if a place which is farther has more entertainment and radius values than the closer one?

**Comment by PropaneDragon** [comment]
I've sort of implemented this now (finally). It'll be in the next update but allows cims to only go to local destinations for shopping in some cases. At night they will only go locally though.
