### ISSUE TITLE
Cities crashing is actually Rush Hour after all

### ISSUE THREAD

**Issue by PropaneDragon** [PropaneDragon/RushHour#57]
Turns out the language selection is completely fucked for some reason. I still need to figure out why it's messed up as much as it is, but it appears to be when it's loading XML language files up or applying languages to the UI.

I also still have no idea why setting Steam to offline mode fixes it...

**Comment by bloodypenguin** [comment]
I didn't looks at code but threading issues is what comes to mind first. Check out which threads have access to that code.

**Comment by PropaneDragon** [comment]
It could very well be, but I'm not entirely sure how I'd check the threads inside the game. It'd be nice if we could attach the VS debugger to it, but that's very unlikely.

**Comment by bloodypenguin** [comment]
Just print current thread name in the problematic code to see which threads invoke it

**Comment by PropaneDragon** [comment]
Fixed in 1.6
