### ISSUE TITLE
Missing file prevents compilation

### ISSUE THREAD

**Issue by r4j4h** [PropaneDragon/RushHour#6]
When I try to compile I get an error

```
Source file 'Places\CityEventManager.cs' could not be found 
```

It stems from the presence of this line:

```
<Compile Include="Places\CityEventManager.cs" />
```

on line 63 of `RushHour/RushHour.csproj`.

I am going to try removing the include and am presuming it will compile fine then, but figured I should bring it to your attention. :)

**Comment by PropaneDragon** [comment]
Yeah, sorry. If you get rid of the line it'll compile fine. I added that before switching branches and didn't carry it over with me.

**Comment by PropaneDragon** [comment]
I've got rid of this on the master branch now, just so you know.

**Comment by r4j4h** [comment]
Great, thanks for letting me know. :)
