### ISSUE TITLE
Commercial demand always high

### ISSUE THREAD

**Issue by seanCodes** [PropaneDragon/RushHour#7]
Installed this mod last night and noticed my commercial demand skyrocketed and stayed high no matter how much I zoned. Just noticed the latest commit (22608effaee96598a6feb886de4614d3228eb75c) was supposed to fix the problem, so I unsubscribed and re-subscribed in Steam to make sure I had the latest version. Unfortunately, it seems I'm still experiencing issue. :confused: I disabled the mod to verify that it was the cause and commercial demand dropped to 0. I don't have any other mods installed that change game mechanics, so I think it must be RushHour.

**Comment by PropaneDragon** [comment]
I'll look into it as soon as I can. My city has zero demand for commercial, so I'll have to figure out why that is and why some people have super high demand.

**Comment by PropaneDragon** [comment]
I've fixed this issue now I think. Could you confirm it's fixed on your end? Thanks.

**Comment by seanCodes** [comment]
Thanks for the quick response! I'll take a look within the next couple hours and let you know.

**Comment by r4j4h** [comment]
I am excited to hear how it fared for seanCodes, but for me, I experienced the super high demand before the update and after the update it seems to have reversed the behavior for me to zero demand.

**Comment by PropaneDragon** [comment]
Ah. It might have been due to the previous high demand and the changing in demand because of the mod. I'll investigate it further. Thanks.

**Comment by PropaneDragon** [comment]
I'm going to guess this is fixed now and close the issue. Let me know if this is not the case, but it has been a while.
