### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by boformer** [PropaneDragon/RushHour#8]
Happened to me twice now: https://gist.github.com/boformer/0d84278ff6d184ec5f62

**Comment by PropaneDragon** [comment]
Did you do anything before the crash happened? I'll take a look at why this is happening now.

**Comment by boformer** [comment]
I placed and deleted roads.

**Comment by PropaneDragon** [comment]
Looks like it might be a conflict with another mod that modifies building AI. I'll have a look into it.

**Comment by boformer** [comment]
The mod list is included. Though I wonder which mod would do this.

**Comment by PropaneDragon** [comment]
So it is. The Traffic Report Tool seems to be a common mod with people that are crashing using this one.

Edit: Never mind about disabling those. Is this upon re-loading a city? If it is then I know the problem and I'll have it fixed soon.

**Comment by boformer** [comment]
I think it happens when you re-load, yes. From main menu.

**Comment by PropaneDragon** [comment]
Ah OK. I know what that problem is, thanks.

**Comment by PropaneDragon** [comment]
This should be fixed for this mod now.
